name: First-workflow

on: push

jobs:
  first_job:
   runs-on: ubuntu-latest
   steps:
    - name: welcome message
      run: echo "myfirst github actions"

    - name: list files in repo
      run: ls

    - name: Read file in repo
      run: cat Sample-Dockerfile