name: First-workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo "My first GitHub Actions"

      - name: List files in repo
        run: ls

      - name: Read file in repo
        run: cat Sample-Dockerfile